//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLogMaster
    {
        public int ErrorID { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ErrorDateTime { get; set; }
        public string UserName { get; set; }
        public string ControllerName { get; set; }
        public string MethodName { get; set; }
        public string InnerErrorMessage { get; set; }
    }
}
